# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-03 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='primary_eng_focus',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='primary_faculty_dept',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='secondary_faculty_dept',
            field=models.CharField(max_length=255),
        ),
    ]
