# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-04 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0002_auto_20161103_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='primary_email',
            field=models.EmailField(max_length=255),
        ),
    ]
