# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-04 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0004_auto_20161104_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='grad_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='project',
            name='primary_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='project',
            name='secondary_email',
            field=models.EmailField(max_length=254),
        ),
    ]
