# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-16 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0005_auto_20161104_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned',
            field=models.NullBooleanField(),
        ),
    ]
