# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-05 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0005_auto_20161104_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='full_desc',
            field=models.CharField(max_length=5024),
        ),
    ]
