# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-18 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20161118_0212'),
        ('submit', '0006_project_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Student'),
        ),
        migrations.AlterField(
            model_name='project',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
