# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-18 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0007_auto_20161118_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assigned_student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Student'),
        ),
    ]
