# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-03 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='background_chk_radio',
            field=models.CharField(default=datetime.datetime(2016, 11, 3, 14, 24, 3, 978477, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='bldr_addr',
            field=models.CharField(default=datetime.datetime(2016, 11, 3, 14, 24, 13, 273200, tzinfo=utc), max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='bldr_email',
            field=models.EmailField(default=datetime.datetime(2016, 11, 3, 14, 24, 36, 408620, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='bldr_phone_number',
            field=models.CharField(default=datetime.datetime(2016, 11, 3, 14, 24, 41, 766538, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='coverletter',
            field=models.FileField(default=datetime.datetime(2016, 11, 3, 14, 24, 47, 426544, tzinfo=utc), max_length=255, upload_to='coverletters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='ethnic_type',
            field=models.CharField(default=datetime.datetime(2016, 11, 3, 14, 24, 52, 510094, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='fall_employment_textarea',
            field=models.CharField(default=datetime.datetime(2016, 11, 3, 14, 24, 56, 88899, tzinfo=utc), max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.CharField(default=datetime.datetime(2016, 11, 3, 14, 24, 59, 526373, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='grad_date_select',
            field=models.CharField(default=datetime.datetime(2016, 11, 3, 14, 25, 2, 421344, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_digits_ssn',
            field=models.CharField(default=datetime.datetime(2016, 11, 3, 14, 25, 5, 676966, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='optradio_research',
            field=models.CharField(default=datetime.datetime(2016, 11, 3, 14, 25, 8, 754162, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='prev_app_radio',
            field=models.CharField(default=datetime.datetime(2016, 11, 3, 14, 25, 11, 969528, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.FileField(default=datetime.datetime(2016, 11, 3, 14, 25, 15, 83740, tzinfo=utc), max_length=255, upload_to='resumes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='school_level_select',
            field=models.CharField(default=datetime.datetime(2016, 11, 3, 14, 25, 18, 585264, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='secondary_major',
            field=models.CharField(default=datetime.datetime(2016, 11, 3, 14, 25, 21, 333166, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_department',
            field=models.CharField(default=datetime.datetime(2016, 11, 3, 14, 25, 24, 590040, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.CharField(default=datetime.datetime(2016, 11, 3, 14, 25, 28, 265266, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='summer_addr',
            field=models.CharField(default=datetime.datetime(2016, 11, 3, 14, 25, 30, 968235, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='summer_email',
            field=models.EmailField(default=datetime.datetime(2016, 11, 3, 14, 25, 33, 712532, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='summer_phone_number',
            field=models.CharField(default=datetime.datetime(2016, 11, 3, 14, 25, 35, 977661, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='year_select',
            field=models.CharField(default=datetime.datetime(2016, 11, 3, 14, 25, 39, 309391, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
