# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20161102_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ethnic_type',
            field=models.CharField(max_length=255),
        ),
    ]
