# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-15 06:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20161103_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='project1',
            field=models.CharField(default=datetime.datetime(2016, 11, 15, 6, 38, 15, 342169, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='project2',
            field=models.CharField(default=datetime.datetime(2016, 11, 15, 6, 38, 20, 491935, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='project3',
            field=models.CharField(default=datetime.datetime(2016, 11, 15, 6, 38, 25, 237774, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='project4',
            field=models.CharField(default=datetime.datetime(2016, 11, 15, 6, 38, 31, 483503, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='project5',
            field=models.CharField(default=datetime.datetime(2016, 11, 15, 6, 38, 36, 792792, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
