# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20161103_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='background_chk_radio',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='coverletter',
            field=models.FileField(default=django.utils.timezone.now, upload_to='coverletters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.FileField(default=django.utils.timezone.now, upload_to='resumes'),
            preserve_default=False,
        ),
    ]
