# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-07 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20161118_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_year_avail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='prev_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='project1requirements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='project2requirements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='project3requirements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='project4requirements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='project5requirements',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='project1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='project2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='project3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='project4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='project5',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
