# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-07 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20161207_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discrimination_training',
            field=models.BooleanField(default=False),
        ),
    ]
