# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-07 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_discrimination_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='discrimination_training',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_year_avail',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='prev_work',
            field=models.CharField(max_length=255),
        ),
    ]
