# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-04 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20161104_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bldr_email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='summer_email',
            field=models.EmailField(max_length=255),
        ),
    ]
