# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-07 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20161207_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='project1requirements',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='project2requirements',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='project3requirements',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='project4requirements',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='project5requirements',
            field=models.CharField(max_length=255),
        ),
    ]
