# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-07 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20161207_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cfactor',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
